### ISSUE TITLE
JsonRecorder missing charset in OutputStreamWriter, JsonLoader uses hardcoded UTF8

### ISSUE THREAD

**Issue by skrilagg** [ppi-ag/deep-sampler#107]
Hi,

just came across an issue with charset/encoding of recorded data:

https://github.com/ppi-ag/deep-sampler/blob/5dee01ca03add7f50f68d2be4a069e2cb4baa9dc/deepsampler-persistence-json/src/main/java/de/ppi/deepsampler/persistence/json/JsonLoader.java#L36

reads the files with UTF8 but in
https://github.com/ppi-ag/deep-sampler/blob/5dee01ca03add7f50f68d2be4a069e2cb4baa9dc/deepsampler-persistence-json/src/main/java/de/ppi/deepsampler/persistence/json/JsonRecorder.java#L53
no charset is configured in the OutputStreamWriter.

We use Cp1252 most of the time and when loading the data from the json file, it's corrupted then.
Maybe I'm missing a configuration that I can adjust.

Regards,
Michel

**Comment by JanSchankin** [comment]
Hi Michel,

version 2.0.1 will come with the following changes:

- Default charset will be `Charset.defaultCharset()` for both `JsonLoader` and `JsonRecorder`. 
- The new annotation `@UseCharset` can be used to configure the charset
- The low-level-api also has a new method to configure the charset: `JsonSourceManager.builder().withCharset("cp1252").buildWithFile()` 

Greetings
Jan
