### ISSUE TITLE
Order of loading JSONs and defining Samplers is messed up

### ISSUE THREAD

**Issue by JanSchankin** [ppi-ag/deep-sampler#57]
IF we want to load JSONS and define Samplers for void methods, we currently have to do something like this:

1. Sampler.of(dao.loadStuff());

2.  load Json

3. Sampler.of(dao.save()).doesNothing()

So the definition of Samplers must be before and after loading the json. This is a bug.
I believe this is caused by 

https://github.com/ppi-ag/deep-sampler/blob/922511f33355f2f9d79679a36f7d06d33edef826/deepsampler-persistence/src/main/java/de/ppi/deepsampler/persistence/api/PersistentSampleManager.java#L82

**Comment by rcschrg** [comment]
In fact this behavior was intended, but obviously a bad idea. The thinking behind it is that you should not mix the pure java-api and the json-persistence API. In reality that doesnt work, so this should be changed.

**Comment by JanSchankin** [comment]
So, this issue is related to #45, maybe we have to rethink the api.
