### ISSUE TITLE
Allow Polymorphic persistenence

### ISSUE THREAD

**Issue by JanSchankin** [ppi-ag/deep-sampler#70]
When DeepSampler wants to deserialize an Object, the concrete type of the object must be known, so that a new instance of that type can be created. 

There are two cases where different deserialization approaches are used:

- Serialization and Deserialization is completely done by the underlying persistence framework (Jackson by default)
- Serialization and Deserialization is done using `PersistentBean`s by DeepSampler`s `PersistentBeanConverter`.

In the first case type information  is completely handled by the persistence framework (Jackson).

In the second case DeepSampler uses the declared return type of the method that is supposed to return the persistent object. Now, there are circumstances where this doesn't work. In general, this is always the case if the actually returned object is a sub type of the declared return type. E.g. in many cases this happens if the declared return type is an interface.

That's why we need to add a type information to `PersistentBean` in all cases where the original type cannot be determined by the declared return type of the sampled method.

**Comment by JanSchankin** [comment]
I've added a branch and a first Testcase to accelerate your kickoff:
https://github.com/ppi-ag/deep-sampler/blob/34c07ff0f40e41975b57a039b6fdb94360b372fa/deepsampler-provider/src/testFixtures/java/de/ppi/deepsampler/provider/common/SamplerAspectTest.java#L1201

**Comment by chb-ppi** [comment]
Test fails now

**Comment by JanSchankin** [comment]
The test was intended to fail until the polymorphic feature is implemented. It should throw an InstantionationError because it is trying to instantiate the interface Animal. Or is it something else? I think the branch is quite old, maybe dev needs to be merged into polymorphic-feature. The test doesn't use PersistentSampler yet.
