### ISSUE TITLE
Check for non-final Classes prevents capturing proxied services.

### ISSUE THREAD

**Issue by skrilagg** [ppi-ag/deep-sampler#94]
Hey all,

I just wanted to let you know, that proxied services cannot be recorded when using something like "target(my.package.MyService)" in a Pointcut when the check "!within(is(FinalType))" is present, see:

https://github.com/ppi-ag/deep-sampler/blob/6c4512fa4bd80dd5515589cbf62888c9f58df2d2/deepsampler-provider-spring/src/main/java/de/ppi/deepsampler/provider/spring/SpringSamplerAspect.java#L70

I had to create a local copy without that condition to get it working.

Best regards
Michel Pittelkow

**Comment by JanSchankin** [comment]
Hi!
Thank you for opening this issue! 

We added this exclusion to the aspect because the Spring context cannot be started  if a final class is part of it - at least this is what we are observing. 
I just reran the tests to see if they still complain about final classes, and they unfortunately do:
```
Caused by: java.lang.IllegalArgumentException: Cannot subclass final class de.ppi.deepsampler.provider.common.FinalTestService
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:660) 
```
`FinalTestService` is a final class that we are using to test if the exclusion `!within(is(FinalType)` is working and if it is necessary. 

Could you provide more information on how the service is proxied? Can you see if the proxy is a final class? The strange thing is, that if the proxy is final, I would expect to see the same Exception as the one above. So maybe there is more going on. 

Maybe  `!within(is(FinalType)` excludes proxies due to some other characteristics of classes, than just the final modifier. In this case we would have to remove the exclusion from the framework. Users would then have to add it in

https://github.com/ppi-ag/deep-sampler/blob/71288cd3d577f3eb6ec1728498d99d384eff68f5/deepsampler-provider-spring/src/test/java/de/ppi/deepsampler/provider/spring/CustomSpringSamplerAspect.java#L27-L28

Greetings
JanSchankin

**Comment by skrilagg** [comment]
Hi Jan,

I am using a Pointcut like this to capture a service using a JDK based Proxy:
"target(de.my.package.IMyService) || this(de.my.package.IMyService)"

I couldn't find out, why the FinalType check prevents the usage of proxied classes, but I have to say: I didn't dig into it really deep, as it works without the FinalType check.

I can't provide you with the realworld example, but maybe this info is enough for you. Maybe this is not a bug but should be mentioned in the documentation or JavaDoc.

Cheers,
Michel

**Comment by JanSchankin** [comment]
Hi Michel,

I'm trying to reproduce this using a Spring Config `@Configuration` with a factory method that returns a proxy. If I create a proxy with javassist, everything works fine. But if I switch to a vanilla jdk Proxy, the Object is ignored by Spring-AOP. I can see in the debugger, that the Object is not enhanced by Spring, it is just the manually created jdk-proxy. 
The behavior doesn't change though, if I remove ` !within(is(FinalType))` from the Aspect. So I'm not 100% there, but there is definitely something strange going on. I will investigate further.

Do you get any Exception, or is the call simply ignored?

Greetings
Jan

**Comment by skrilagg** [comment]
Hi Jan,

I didn't get any Exceptions the call was simply ignored. I just tried to dig a little bit into the framework part that is handling those services and maybe this helps reproduce the issue:

- The Framework is using a BeanFactoryPostProcessor to register the Services using the spring-internal Tools
- RootBeanDefinitions are generated with AUTOWIRE_BY_TYPE and Scope "request" 
- BeanDefinitionHolder is then used to generate a "ScopedProxy" using springs ScopedProxyUtils#createScopedProxy
- The BeanDefinition of the proxy is then set to init lazily and registered using springs BeanDefinitionReaderUtils#registerBeanDefinition.

Maybe I can create some kind of snippet and provide you with it to reproduce the issue.

Cheers,
Michel

**Comment by JanSchankin** [comment]
Hi Michel,

I think I can reproduce this now. According to [Baeldung 3.3 this and target](https://www.baeldung.com/spring-aop-pointcut-tutorial#3-this-and-target) Spring treats Proxies different for JdkProxies and CGLIB-Proxies. 

In my first attempts I used a PointCut `within(...)` not `this(...)` and `target(...)` , as you originally described it. After adding `target(de.ppi.deepsampler.provider.common.ProxiedTestService) || this(de.ppi.deepsampler.provider.common.ProxiedTestService)` , the method call is ignored if `!within(is(FinalType))`  is part of the PointCutExpression. If I remove this exclusion, the method gets stubbed.

I don't yet understand the connection to `final`, though.  

Greetings
Jan

**Comment by JanSchankin** [comment]
The SpringSamplerAspect will haven an extra PointCut signature in 2.0.0, that can be overridden in sub classes. This enables users to change the default PointCut completely.

https://github.com/ppi-ag/deep-sampler/blob/ca9a6f2f7507999f89df2e89e7e17387749fc0ec/deepsampler-provider-spring/src/main/java/de/ppi/deepsampler/provider/spring/SpringSamplerAspect.java#L78-L83

The test

https://github.com/ppi-ag/deep-sampler/blob/e267acdb2260538b5d3f63b94ebacce8ed1eafff/deepsampler-provider-spring/src/test/java/de/ppi/deepsampler/provider/spring/jdkproxy/ProxiedServiceTest.java#L29-L30

should reproduce the described situation. It runs green if the defaultPointCut is changed like this:

https://github.com/ppi-ag/deep-sampler/blob/e267acdb2260538b5d3f63b94ebacce8ed1eafff/deepsampler-provider-spring/src/test/java/de/ppi/deepsampler/provider/spring/jdkproxy/ProxiedServiceSpringSamplerAspect.java#L34-L40
